//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetBankList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class getbanklist
    {
        public System.DateTime datestamp { get; set; }
        public string apiname { get; set; }
        public string request { get; set; }
        public string addInfo10 { get; set; }
        public string addInfo9 { get; set; }
        public string androidId { get; set; }
        public string appName { get; set; }
        public string appVersionCode { get; set; }
        public string appVersionName { get; set; }
        public string bluetoothMac { get; set; }
        public string capability { get; set; }
        public string deviceId { get; set; }
        public string deviceType { get; set; }
        public string geoCode { get; set; }
        public string ip { get; set; }
        public string location { get; set; }
        public string mobileNo { get; set; }
        public string os { get; set; }
        public string regId { get; set; }
        public string selectedSimSlot { get; set; }
        public string simId { get; set; }
        public string wifiMac { get; set; }
        public string pspId { get; set; }
        public string pspRefNo { get; set; }
        public string profileId { get; set; }
    }
}
